##
# Blesta Docker Setup by Exonical <opensource@terrahost.cloud>
##
version: '2.1'
services:
##
# MariaDB (MySQL) Server
# If you rely on another MySQL/MariaDB instance, 
# this can be safely removed.
##
  mysql:
    image: mariadb:10.5
    restart: always
    volumes:
    - ./db:/var/lib/mysql


##
# Blesta
# This is the main service that will be seen publically.
##
  blesta:
    depends_on:
    - mysql
    image: terrahost/docker-blesta:latest
    restart: always
    volumes:
    - ./data:/data
    ports:
    - 80:80
    - 443:443
